name: Dummy CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-docker-image .

      # (Optional) Step 4: Push Docker image to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag my-docker-image my-dockerhub-username/my-docker-image:latest
          docker push my-dockerhub-username/my-docker-image:latest

  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait Before Linting
        run: sleep 20

      - name: Lint Code
        run: echo "Linting repository... Done!"

      - name: Wait Before Running Tests
        run: sleep 20

      - name: Run Unit Tests
        run: echo "Running unit tests... All tests passed!"

  build-and-push-dummy-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait Before Simulating Build and Push
        run: sleep 20

      - name: Simulate Build and Push
        run: |
          echo "Building a dummy Docker image... Done!"
          echo "Pushing the dummy image to a hypothetical registry... Done!"

  continuous-deployment:
    name: Continuous Deployment
    needs: build-and-push-dummy-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait Before Simulating Deployment
        run: sleep 20

      - name: Simulate Deployment
        run: |
          echo "Deploying the dummy application... Done!"
          echo "Dummy deployment successful!"